### ISSUE TITLE
Docs Please???

### ISSUE THREAD

**Issue by TheWebMachine** [SolderedElectronics/Inkplate_Motion_Arduino_Library#10]
Already got my Inkplate 6 Motion today but I see the docs are still not available. I have no idea how to use the new programmer and I also get errors in Arduino even attempting to verify an example's code without upload.

````
/home/user/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1/system/extras/prebuild.sh: 17: Bad substitution
sh /home/user/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1/system/extras/prebuild.sh /home/user/.cache/arduino/sketches/015B96E7B1E06D62BA801F9E29E7C36A /tmp/.arduinoIDE-unsaved202511-194520-1szmn28.9a78/Inkplate_6_Motion_Factory_Programming /home/user/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1
exit status 2

Compilation error: exit status 2
````

Any update on when the full docs will be available? Thanks!

**Comment by rsoric** [comment]
Hi @TheWebMachine ,

really sorry about the docs, they are being finished as I write this, we are using a brand new system for documentation and are writing Inkplate 6MOTION as new docs from scratch. I'll write here and close the issue only when the new docs are online and available to read. Thank you for your patience.

As for your issue with uploading code, I've consulted with @BornaBiro - are you using Arduino 2.0 or newer? Due to us using the STM32 board definition, it requires Arduno 2.0 or newer. Try that and let me know please

-Rob

**Comment by TheWebMachine** [comment]
Yup. v2.3.4

![Image](https://github.com/user-attachments/assets/a61a1c89-8ea5-4bdd-97da-c2d4f7792dad)

I'm on Ubuntu 22.04. I have the STM32 Cube app installed, as well. Arduino IDE is properly un-sandboxed and I can select the board and port in the IDE, but get the error shown in my OP when trying to upload an example.

Just don't know how all of this is supposed to fit together. 🤷 So, perhaps the docs will highlight what I'm missing...

As an aside, the use of STM32 is quite the departure in the Inkplate line. Was it necessary to meet the higher refresh rate of the 6MOTION's display?

**Comment by rsoric** [comment]
Hi @TheWebMachine ,

we just finished the Inkplate 6 MOTION docs, see [here](https://docs.inkplate.com/)

As for your question, yes, using the STM32 and DRAM was necessary due to the speed of sending the data to the e-Paper and processing it.

Have you had any updates regarding attempting to compile and upload code?

-Rob

**Comment by TheWebMachine** [comment]
So, after reviewing the docs, I'm still stuck. Still getting the error message. Taking a deeper look this time, I see line 17 in `prebuild.sh` is:

`  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH//\\/\\\\}" > "$BUILD_PATH/sketch/build.opt"`

This is throwing a bad substitution error on my system. I'm on Ubuntu 22.04 and Arduino 2.x is installed via AppImage, which is Arduino's default supported install method on Linux. I have confirmed that the board is visible to Arduino (udev and other perms are set properly) as I can see `00:49:22.581 -> Programming mode active.` via Serial Monitor when plugging into my laptop.

This would appear to simply be an issue with the prebuild script for a new sketch preparation. I'm not sure how to correct the printf substitution to preclude the error.

I thought perhaps it was because I had loaded an example and had not saved it as its own independent sketch folder. However, even after saving the sketch example proper, I get the same error:

````
FQBN: Inkplate_Motion:stm32:Inkplate6Motion
Using board 'Inkplate6Motion' from platform in folder: /home/thewebmachine/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1
Using core 'arduino' from platform in folder: /home/thewebmachine/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1

sh /home/thewebmachine/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1/system/extras/prebuild.sh /home/thewebmachine/.cache/arduino/sketches/38F9BF010B9BC5C4728A342D3744172A /home/thewebmachine/ownCloud-local/Arduino/InkPlate6Motion/Inkplate_6_Motion_Factory_Programming /home/thewebmachine/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1
/home/thewebmachine/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.1/system/extras/prebuild.sh: 17: Bad substitution
exit status 2

Compilation error: exit status 2
````

**Comment by TheWebMachine** [comment]
Alright. With some tinkering, I've managed to get one of the included examples (fast animation) to build and upload. I altered prebuild.sh line 17 to remove the attempt to convert the `BOARD_PLATFORM_PATH` from absolute to relative:

````
  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH}" > "$BUILD_PATH/sketch/build.opt"
````

Everything compiled (a warning was thrown, see below) but compile was ultimately successful and I was able to upload the sketch without incident.

So, I also edited line 23 to remove the variable expansion there, to match line 17. What is the purpose of switching to a relative path?? I see no ill effects from using an absolute path so far. Am I missing something?

Also, the warning I am seeing on compile is this:

````
In file included from /home/thewebmachine/ownCloud-local/Arduino/libraries/Inkplate_Motion_Library/src/system/../boards/Inkplate6Motion/waveforms.h:9,
                 from /home/thewebmachine/ownCloud-local/Arduino/libraries/Inkplate_Motion_Library/src/system/../boards/Inkplate6Motion/IP6MotionDriver.h:20,
                 from /home/thewebmachine/ownCloud-local/Arduino/libraries/Inkplate_Motion_Library/src/system/InkplateBoards.h:19,
                 from /home/thewebmachine/ownCloud-local/Arduino/libraries/Inkplate_Motion_Library/src/InkplateMotion.h:22,
                 from /home/thewebmachine/ownCloud-local/Arduino/InkPlate6Motion/Inkplate_6_Motion_Fast_Animation/Inkplate_6_Motion_Fast_Animation.ino:14:
/home/thewebmachine/ownCloud-local/Arduino/libraries/Inkplate_Motion_Library/src/system/../boards/Inkplate6Motion/../../system/defines.h:51:1: warning: 'typedef' was ignored in this declaration
   51 | typedef struct InkplateWaveform
      | ^~~~~~~
````

The warning doesn't seem to break anything, but I figured you would want to know about it. Anyway, unless there is some critical purpose to a relative board platform path, it might be prudent to switch prebuild.sh to use only an absolute path for maximal compatibility for all users. I was going to go submit a pull request for this change, but I'm not seeing that file in the board definition repo (SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE). 🤷 

For completeness, here is my modified prebuild.sh:

````
#!/bin/bash

BUILD_PATH="$1"
BUILD_SOURCE_PATH="$2"
BOARD_PLATFORM_PATH="$3"

# Create sketch dir if not exists
if [ ! -f "$BUILD_PATH/sketch" ]; then
  mkdir -p "$BUILD_PATH/sketch"
fi

# Create empty build.opt if build_opt.h does not exists in the original sketch dir
# Then add or append -fmacro-prefix-map option.
# (i.e. the folder containing boards.txt)
if [ ! -f "$BUILD_SOURCE_PATH/build_opt.h" ]; then
  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH}" > "$BUILD_PATH/sketch/build.opt"
else
  # Else copy the build_opt.h as build.opt
  # Workaround to the header file preprocessing done by arduino-cli
  # See https://github.com/arduino/arduino-cli/issues/1338
  cp "$BUILD_SOURCE_PATH/build_opt.h" "$BUILD_PATH/sketch/build.opt"
  printf '\n-fmacro-prefix-map="%s"=.' "${BOARD_PLATFORM_PATH}" >> "$BUILD_PATH/sketch/build.opt"
fi


# Force include of SrcWrapper library
echo "#include <SrcWrapper.h>" > "$BUILD_PATH/sketch/SrcWrapper.cpp"
````

**Comment by TheWebMachine** [comment]
No problem at all! I've been supporting/purchasing InkPlate models from nearly the beginning of the project. That said, I did see mention in the docs that you are looking to expand ESPHome/HomeAssistant support. I am a poweruser/adopter of both projects and own the following InkPlate models:

- 4 TEMPERA
- 5
- 6PLUS
- 6COLOR
- 6MOTION
- 10

I would happily help test and build out ESPHome support for the InkPlate series, as I've already been tinkering around with ESPHome on my devices. I even managed to hobble together support (including some of the sensors) for the 4 TEMPERA recently using the inkplate6 display platform despite not yet being officially supported. I wish I was better with LVGL, but I digress. haha

**Comment by rsoric** [comment]
That's awesome! I'd love to continue our conversation about this, could you get in touch with us us [here](https://soldered.com/contact/)? Thanks!

**Comment by TheWebMachine** [comment]
> That's awesome! I'd love to continue our conversation about this, could you get in touch with us us [here](https://soldered.com/contact/)? Thanks!

Sent! 😎

**Comment by rsoric** [comment]
We pushed a new release of our [Dasduino boards definition boards index with this fix](https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/commit/b5ee4f5b2675c22da9fc330d286f53e033418167), I've also included a comment which links to this issue. It worked on my windows machine well, too. 

Closing this for now, hopefully no other user will have this problem. Also likely we're going to open an issue on STM32duino repository mentioning this fix to see what they have to say, why not share the code even wider.

Thanks again!

**Comment by frankgerhardt** [comment]
I still have the issue with the newer version 1.0.2. 

```
/home/user/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.2/system/extras/prebuild.sh: 17: Bad substitution
exit status 2

Compilation error: exit status 2
```

Can I pls get a fix asap!? I've spent hours on setting this up and could not do anything with the hardware yet. In all my desperation I even looked at the closed issues in this repo only to find out that you have this problem already and closed the issue.  :-( :-( :-(

**Comment by TheWebMachine** [comment]
> /home/user/.arduino15/packages/Inkplate_Motion/hardware/stm32/1.0.2/system/extras/prebuild.sh

To confirm, can you show us the content of that file? I would like to compare to my own fix.
